# **EXPLORATION**

## LIBRARIES

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

In [2]:
import sys
import os

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from exploration import *
from template_code import *
from utils import *

## LOAD DATA

In [3]:
dataset_original = load_dataset('../data/atlanta_restaurant_slice_2023.csv')

In [4]:
dataset_original.head()

,title,categoryName,website,url,reviewsCount,stars,text
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...

| Column Name | Description |
|-------------|-------------|
| title | Name of the restaurant |
| categoryName | Labels that describe the restaurant's cuisine type |
| website | URL of the restaurant's webpage |
| url | URL of the restaurant's Google Maps page |
| reviewsCount | Total number of reviews for the restaurant at the time of scraping |
| stars | Customer rating (1 to 5) |
| text | Text of the review |

In [5]:
dataset = dataset_original.copy()

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53566 entries, 0 to 53565
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         53566 non-null  object
 1   categoryName  53566 non-null  object
 2   website       50600 non-null  object
 3   url           53566 non-null  object
 4   reviewsCount  53566 non-null  int64
 5   stars         53566 non-null  float64
 6   text          53566 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ MB

In [7]:
dataset.shape

(53566, 7)

In [8]:
# How many reviews are we analysing?
dataset.shape[0]

53566

In [9]:
# How many unique restaurants are there?
dataset['title'].nunique()

295

In [10]:
# How many categories are there?
dataset['categoryName'].nunique()

19

In [11]:
# Which categories are we analysing?
dataset['categoryName'].unique()

array(['Seafood restaurant', 'Italian restaurant', 'Mexican restaurant',
       'New American restaurant', 'Japanese restaurant',
       'Fast food restaurant', 'American restaurant',
       'Hamburger restaurant', 'Breakfast restaurant',
       'Indian restaurant', 'Mediterranean restaurant', 'Thai restaurant',
       'Steak house', 'Barbecue restaurant', 'Bar & grill',
       'Chinese restaurant', 'Pizza restaurant', 'Chicken restaurant',
       'Sandwich shop'], dtype=object)

In [13]:
# How many reviews per category?
dataset['categoryName'].value_counts()

Mexican restaurant          8959
Fast food restaurant        5325
Italian restaurant          5108
American restaurant         5049
Pizza restaurant            4560
Breakfast restaurant        2491
Chinese restaurant          2484
Seafood restaurant          2048
Hamburger restaurant        1979
New American restaurant     1903
Sandwich shop               1862
Chicken restaurant          1780
Steak house                 1776
Indian restaurant           1753
Japanese restaurant         1533
Mediterranean restaurant    1450
Thai restaurant             1260
Barbecue restaurant         1139
Bar & grill                 1107
Name: categoryName, dtype: int64

In [17]:
# How many restaurants per category?
dataset['title'].groupby(dataset['categoryName']).nunique()

categoryName
American restaurant         36
Bar & grill                  7
Barbecue restaurant          7
Breakfast restaurant         8
Chicken restaurant           8
Chinese restaurant          16
Fast food restaurant        16
Hamburger restaurant        11
Indian restaurant            9
Italian restaurant          30
Japanese restaurant          9
Mediterranean restaurant     9
Mexican restaurant          52
New American restaurant     15
Pizza restaurant            23
Sandwich shop                8
Seafood restaurant          15
Steak house                  8
Thai restaurant              9
Name: title, dtype: int64

In [20]:
# Which restaurants per category?
dataset['title'].groupby(dataset['categoryName']).value_counts()

categoryName         title
American restaurant  Ted's Montana Grill               426
                     O'Charley's Restaurant & Bar      233
                     Sage Woodfire Tavern Perimeter    232
                     Lazy Dog Restaurant & Bar         230
                     Tam's BackStage                   227
                                                      ...
Thai restaurant      Red Elephant Thai Cuisine         176
                     Bangkok Thai Restaurant            79
                     Tuk Tuk Thai Food Loft             76
                     Nan Thai Fine Dining               69
                     Shai Karr Eatery                   29
Name: title, Length: 296, dtype: int64

In [13]:
# How many reviews does the most reviewed restaurant have?
dataset['title'].value_counts().max()

1140

In [41]:
# How many reviews per restaurant are we analysing?
dataset['title'].value_counts()

Chick-fil-A                                1140
Waffle House                                852
Wendy's                                     810
McDonald's                                  665
Zaxby's Chicken Fingers & Buffalo Wings     588
                                           ...
TWO urban licks                              22
The Bistro – Eat. Drink. Connect.®           16
The Terrace                                  16
The Courtside Grille                         11
Fork & Juniper Restaurant                     8
Name: title, Length: 295, dtype: int64

In [45]:
# How many reviews does each restaurant have, in reality?
dataset_original[['title', 'reviewsCount']].drop_duplicates().sort_values(by='reviewsCount', ascending=False)

                                              title  reviewsCount
50188                    Pappadeaux Seafood Kitchen         13268
2287                 Old Lady Gang Southern Cuisine          9933
1296                                TWO urban licks          8057
2721   Six Feet Under Pub & Fish House - Grant Park          6817
1458                                No Mas! Cantina          6300
...                                             ...           ...
625              The Bistro – Eat. Drink. Connect.®            21
40188                                   The Terrace            18
4394                           The Courtside Grille            17
1055                      Fork & Juniper Restaurant             9
641                                  Johnny Rockets             5

[349 rows x 2 columns]

In [ ]:
# DATAFRAME COM RESTAURANTS, NR TOTAL DE REVIEWS, NR REVIEWS ANALYSED, DIFERENCE

In [25]:
# Each restaurant belongs to only one category, right? If not wichh ones belong to more than one?
dataset.groupby('title')['categoryName'].nunique().sort_values(ascending=False).head(10)

title
J. Christopher's                   2
3 Amigos Mexican Bar & Grill       1
No Mas! Cantina                    1
Olive Garden Italian Restaurant    1
Old Lady Gang Southern Cuisine     1
Old Harbor Seafood Kitchen         1
O'Charley's Restaurant & Bar       1
Novo Cucina                        1
North Italia                       1
Nino's Italian Restaurant          1
Name: categoryName, dtype: int64

In [27]:
# How many reviews per rating?
dataset['stars'].value_counts()

5.0    33299
1.0     7194
4.0     6800
3.0     3534
2.0     2739
Name: stars, dtype: int64

In [31]:
# Describe rating per category
dataset.groupby('categoryName')['stars'].describe()

                           count      mean       std  min  25%  50%  75%  max
categoryName
American restaurant       5049.0  4.220440  1.308092  1.0  4.0  5.0  5.0  5.0
Bar & grill               1107.0  4.274616  1.226042  1.0  4.0  5.0  5.0  5.0
Barbecue restaurant       1139.0  4.266023  1.281337  1.0  4.0  5.0  5.0  5.0
Breakfast restaurant      2491.0  4.173826  1.344890  1.0  4.0  5.0  5.0  5.0
Chicken restaurant        1780.0  3.482022  1.700845  1.0  1.0  4.0  5.0  5.0
Chinese restaurant        2484.0  3.842593  1.554417  1.0  3.0  5.0  5.0  5.0
Fast food restaurant      5325.0  3.369014  1.696656  1.0  1.0  4.0  5.0  5.0
Hamburger restaurant      1979.0  4.156645  1.337686  1.0  4.0  5.0  5.0  5.0
Indian restaurant         1753.0  4.174558  1.376703  1.0  4.0  5.0  5.0  5.0
Italian restaurant        5108.0  4.322631  1.253802  1.0  4.0  5.0  5.0  5.0
Japanese restaurant       1533.0  4.117417  1.415797  1.0  4.0  5.0  5.0  5.0
Mediterranean restaurant  1450.0  4.315172  1.284017  1.0  4.0  5.0  5.0  5.0
Mexican restaurant        8959.0  4.061502  1.448957  1.0  3.0  5.0  5.0  5.0
New American restaurant   1903.0  4.291645  1.229487  1.0  4.0  5.0  5.0  5.0
Pizza restaurant          4560.0  4.105482  1.426127  1.0  4.0  5.0  5.0  5.0
Sandwich shop             1862.0  3.735231  1.618749  1.0  2.0  5.0  5.0  5.0
Seafood restaurant        2048.0  4.246582  1.277836  1.0  4.0  5.0  5.0  5.0
Steak house               1776.0  4.225788  1.328869  1.0  4.0  5.0  5.0  5.0
Thai restaurant           1260.0  4.257143  1.296628  1.0  4.0  5.0  5.0  5.0

In [33]:
# Describe rating per restaurant
dataset.groupby('title')['stars'].describe()

,count,mean,std,min,25%,50%,75%,max
title,,,,,,,,
3 Amigos Mexican Bar & Grill,182.0,4.549451,1.005661,1.0,5.0,5.0,5.0,5.0
5Church Buckhead,73.0,4.095890,1.396070,1.0,4.0,5.0,5.0,5.0
AG,62.0,4.500000,0.844461,2.0,4.0,5.0,5.0,5.0
ANNUNZIATA'S Pizza & Pasta,224.0,4.361607,1.335460,1.0,5.0,5.0,5.0,5.0
AZN Sandwich Bar,101.0,4.574257,0.973104,1.0,5.0,5.0,5.0,5.0
...,...,...,...,...,...,...,...,...
Yard House,59.0,3.830508,1.599057,1.0,2.5,5.0,5.0,5.0
Your Pie Pizza,386.0,4.349741,1.243983,1.0,4.0,5.0,5.0,5.0
Yume Ramen Bar in Peachtree City,215.0,4.013953,1.392500,1.0,3.0,5.0,5.0,5.0
Zaxby's Chicken Fingers & Buffalo Wings,588.0,3.585034,1.620119,1.0,2.0,4.0,5.0,5.0
il Giallo Osteria & Bar,208.0,4.519231,0.967898,1.0,4.0,5.0,5.0,5.0

In [ ]:
# Map visualization ratings