# **EXPLORATION**

## LIBRARIES

In [1]:
import sys
import os
import pandas as pd

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from utils import *
from exploration import *
from template_code import *

In [2]:
dataset_original = load_dataset('../data/atlanta_restaurant_slice_2023.csv')

In [3]:
dataset_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53566 entries, 0 to 53565
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         53566 non-null  object
 1   categoryName  53566 non-null  object
 2   website       50600 non-null  object
 3   url           53566 non-null  object
 4   reviewsCount  53566 non-null  int64
 5   stars         53566 non-null  float64
 6   text          53566 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ MB

| 🏷️ **Column Name** | 📝 **Description** |
|:-------------------|:-------------------|
|**title** | Name of the restaurant |
|**categoryName** | Labels that describe the restaurant's cuisine type |
|**website** | URL of the restaurant's webpage |
|**url** | URL of the restaurant's Google Maps page |
|**reviewsCount** | Total number of reviews for the restaurant at the time of scraping |
|**stars** | Customer rating (1 to 5) |
|**text** | Text of the review |

In [4]:
dataset = dataset_original.copy()

## 1. Dataset Structure & Integrity

In [5]:
# TODO: How many unique restaurants are there?
dataset['title'].nunique()

295

In [6]:
# TODO: How many reviews?
dataset.shape[0]

53566

In [7]:
# TODO: Are there missing records?
dataset.isnull().sum()

title              0
categoryName       0
website         2966
url                0
reviewsCount       0
stars              0
text               0
dtype: int64

In [8]:
missing_website_rows = dataset[dataset['website'].isnull()]
print(f"Number of rows with missing website: {len(missing_website_rows)}")
missing_website_rows[['title', 'categoryName', 'website', 'url', 'stars']].head(10)
restaurants_missing_website = missing_website_rows['title'].unique()
restaurants_missing_website

Number of rows with missing website: 2966

array(['Egg Harbor Cafe', 'Mi Barrio Mexican Restaurant',
       'Jalisco Restaurant', 'J.A.T.C Cuisine ATL',
       'The Courtside Grille', 'Little Thai Cuisine',
       'Savor Bar & Kitchen', 'Cinco Mexican Cantina', "Farmer's Basket",
       'Marisqueria El Escandalo', 'Smokey Q BBQ', 'El Rio Cantina',
       'Mexican Grill', 'Balsas Mexican Restaurant', 'LA MEXICANA',
       'PITA Mediterranean Street Food', 'Big Daddy’s Oyster Bar',
       'The Terrace', 'Padella Italian Atlanta', 'Mi Rancho #2',
       'Marietta Crawfish', 'Philly & Wraps',
       'PITA Mediterranean Street Food-Marietta Square', 'MamiTaco',
       'Costa Mar Seafood & Grill', 'Ege Sushi & Japanese Cuisine'],
      dtype=object)

In [9]:
# Check if restaurants are completely missing website information
# or if they only have missing websites for some of their reviews
print("Restaurants that have NO website information across ALL their reviews:")
for rest in restaurants_missing_website:
    # Compare total number of reviews for this restaurant with number of missing website values
    total_reviews = dataset[dataset['title'] == rest].shape[0]
    missing_website_count = dataset[dataset['title'] == rest]['website'].isnull().sum()
    
    if total_reviews == missing_website_count:
        print(f"- {rest}")

print("\nConclusion: All restaurants listed above have NO website information in any of their reviews.")
print("This suggests these restaurants either don't have websites or the website data wasn't available during scraping.")

Restaurants that have NO website information across ALL their reviews:
- Egg Harbor Cafe
- Mi Barrio Mexican Restaurant
- Jalisco Restaurant
- J.A.T.C Cuisine ATL
- The Courtside Grille
- Little Thai Cuisine
- Savor Bar & Kitchen
- Cinco Mexican Cantina
- Farmer's Basket
- Marisqueria El Escandalo
- Smokey Q BBQ
- El Rio Cantina
- Mexican Grill
- Balsas Mexican Restaurant
- LA MEXICANA
- PITA Mediterranean Street Food
- Big Daddy’s Oyster Bar
- The Terrace
- Padella Italian Atlanta
- Mi Rancho #2
- Marietta Crawfish
- Philly & Wraps
- PITA Mediterranean Street Food-Marietta Square
- MamiTaco
- Costa Mar Seafood & Grill
- Ege Sushi & Japanese Cuisine

Conclusion: All restaurants listed above have NO website information in any of their reviews.
This suggests these restaurants either don't have websites or the website data wasn't available during scraping.
- Padella Italian Atlanta
- Mi Rancho #2
- Marietta Crawfish
- Philly & Wraps
- PITA Mediterranean Street Food-Marietta Square
- MamiTaco
- Costa Mar Seafood & Grill
- Ege Sushi & Japanese Cuisine

Conclusion: All restaurants listed above have NO website information in any of their reviews.
This suggests these restaurants either don't have websites or the website data wasn't available during scraping.

In [11]:
# TODO: Are there duplicated records?
dataset.duplicated().sum()

99

## 2. Restaurants

In [13]:
# TODO: How many unique restaurants?
dataset['title'].nunique()

295

In [14]:
# TODO: Which restaurants do we have?
dataset['title'].unique()

array(['The Optimist', "Nino's Italian Restaurant", 'El Valle',
       'Longleaf Restaurant', 'Benihana', "Mama's Restaurant",
       'Dirty Rascal', 'Chick-fil-A', 'KR SteakBar',
       'The Bistro – Eat. Drink. Connect.®', 'Johnny Rockets',
       'Grindhouse Killer Burgers', '5Church Buckhead', 'Egg Harbor Cafe',
       'El Azteca', 'Mi Barrio Mexican Restaurant', 'Grana',
       'Fork & Juniper Restaurant', 'NaanStop', 'Yard House', 'Atalian',
       'TWO urban licks', 'Aria', 'Miller Union', 'No Mas! Cantina',
       "Houston's", 'Staplehouse', 'Alma Cocina Downtown', 'Atlas',
       'Aviva by Kameel Downtown', 'La Grotta Ristorante',
       'Nan Thai Fine Dining', 'La Tavola Trattoria', 'Bacchanalia',
       'Bones Restaurant', 'Canoe', 'Old Lady Gang Southern Cuisine',
       'Jalisco Restaurant', "Fat Matt's Rib Shack",
       'Bangkok Thai Restaurant', 'BrickStone Cafe & Restaurant',
       'Argosy', 'Atlanta Fish Market',
       'Six Feet Under Pub & Fish House - Grant Park',
       'Local Three Kitchen & Bar', 'Eats', 'Gunshow', 'AG', 'Lure',
       'Tuk Tuk Thai Food Loft', 'Treehouse Restaurant and Pub',
       'Hard Rock Cafe', 'J.A.T.C Cuisine ATL', 'The Southern Gentleman',
       'Sarku Japan', 'La Parrilla Mexican Restaurant',
       'Abuelos Mexican Kitchen and Cantina',
       'Napoli New York Pizza Italian Kitchen & Catering', 'Tre Vele',
       'The Courtside Grille', 'Casi Cielo', "McDonald's", 'Flower Child',
       'Chin Chin 5', 'Milano Pizza & Subs', "Wendy's",
       'Hearth Pizza Tavern', 'Blue Moon Pizza Sandy Springs',
       'The Select', "Vinny's N.Y. Pizza & Grill - Sandy Springs",
       'il Giallo Osteria & Bar', 'Kid Cashew', "J. Christopher's",
       "Chupito's Azteca Grille", 'Taquito Express - Mt Vernon',
       'Bay Leaf Indian Cuisine', 'Viceroy Indian Dining',
       'Little Thai Cuisine', 'NFA Burger', 'Lucky China',
       'Brooklyn Cafe', 'Shake Shack Perimeter Mall', 'Ruscello',
       'Hyderabad House Atlanta - Biryani Place', 'Savor Bar & Kitchen',
       'Cinco Mexican Cantina', 'Taqueria Los Hermanos',
       "Del Frisco's Double Eagle Steakhouse",
       'Royal Spice Indian Restaurant', 'North Italia',
       'Red Pepper Taqueria - Dunwoody',
       'Cafe Sababa - Mediterranean Grill', 'Village Burger',
       "Joey D's Oak Room", "McKendrick's Steak House",
       'Olive Garden Italian Restaurant', 'Biryanis Place Sandy Springs',
       'Carbonara Trattoria', "Marlow's Tavern", 'Seasons 52',
       "Maggiano's Little Italy", 'Sage Woodfire Tavern Perimeter',
       'Lazy Dog Restaurant & Bar', 'Novo Cucina', 'Farm Burger Dunwoody',
       "J. Alexander's Restaurant", 'Buon Fornello Café & Bottega',
       'Baraonda Ristorante & Bar', 'Mellow Mushroom Sandy Springs',
       'Waffle House', 'Chopsticks at Dunwoody', 'QDOBA Mexican Eats',
       'Superica', "Farmer's Basket",
       "Taziki's Mediterranean Cafe - Sandy Springs",
       'Happy Family Chinese Food And Sushi Bar', "Arby's",
       'Marisqueria El Escandalo', 'Mellow Mushroom Cumming', 'Taco Bell',
       "Jim 'N Nick's Bar-B-Q", 'First Watch', 'Lake Burrito',
       'Fridas Mexican Cuisine', "Shuckin' Shack Oyster Bar",
       'Branchwater', 'KFC', 'CAVA', 'Osaka Steak And Sushi',
       "Ted's Montana Grill", "Carrabba's Italian Grill",
       'Firehouse Subs Cumming Marketplace', 'Panda Express',
       'Pueblos Mexican Cuisine', 'Papa Johns Pizza',
       'Little Caesars Pizza', "Baba's Gyro & Kabob", "Jimmy John's",
       'Popeyes Louisiana Kitchen', 'Sawnee Mountain Biscuit Co.',
       'Smokey Q BBQ', "Jersey Mike's Subs", 'Taqueria Saribella, LLC',
       'Lennys Grill & Subs', 'Deckers Express', 'Subway',
       "Zaxby's Chicken Fingers & Buffalo Wings",
       'Dairy Queen Grill & Chill', "Johnny's New York Style Pizza",
       'Cue Barbecue', 'Summits Wayside Tavern', 'Socks Love Barbecue',
       'Hong Kong Chinese Restaurant', 'La Zacatecana Taqueria',
       'Dragon Buffet', 'IHOP', "ANNUNZIATA'S Pizza & Pasta",
       'Five Boroughs Pizza Tavern', "Big D's BBQ",
       'Old Harbor Seafood Kitchen', 'Huddle House', 'El Rio Cantina',
       'Cracker Barrel Old Country Store', 'Your Pie Pizza',
       'Mexican Grill', "Marie's Italian Deli, Bakery & Market",
       "Captain D's", "Rooster's Cafe", "O'Charley's Restaurant & Bar",
       "Good ol' Days Bar and Grill", 'Hacienda Bar & Grill',
       'Tacos & Tequilas Mexican Grill', 'Taco mexico',
       'Savory Mexican Restaurant', 'LongHorn Steakhouse',
       'Outback Steakhouse', 'Los Rios', 'Texas Roadhouse',
       'The Ridge-Great Steaks and Seafood', 'The Station House',
       "Tam's BackStage", 'MOD Pizza', "Provino's Italian Restaurant",
       "Cheeseburger Bobby's", "Steak 'n Shake", 'Hardee’s',
       'Balsas Mexican Restaurant', 'Chipotle Mexican Grill', 'Krystal',
       'Due South Seafood Kitchen', 'The Italian Oven Restaurant', 'Goto',
       'Five Guys', "Jet's Pizza®", "McAlister's Deli",
       'Firehouse Subs Westpark Walk',
       'LA PAPA "Hot potato & Corn House"', 'LA MEXICANA',
       'Partners II Pizza Braelinn', "Schlotzsky's",
       "Dickey's Barbecue Pit", "Buck's Pizza", 'Partners II Pizza',
       "Marco's Pizza", 'Star Of India', 'Georgia Shrimp Co',
       'Chin Chin Chinese', 'Chopsticks China Bistro',
       'El Ranchero 7 Bar & Grill', 'Ichiban Japanese Sushi Bar & Grill',
       'Los Mariachis', 'Ranchero Bar & Grill (Westpark)',
       'Super Chix - Peachtree City, GA',
       'Yume Ramen Bar in Peachtree City',
       'La Hacienda Mexican Restaurant', 'Charm Thai Cuisine',
       'PITA Mediterranean Street Food',
       'Azul Tequila Taqueria & Cantina', 'Borgo Italia',
       'Big Daddy’s Oyster Bar',
       'Kobe Japanese Steakhouse in Peachtree City, GA',
       'Peachtree City Yacht Club', 'Casa Vieja', 'Thai Spice',
       "Palmer's", 'Grazing Here', 'Choong Man Chicken Peachtree City',
       'The Terrace', 'Happy China', 'Wok Express Chinese Restaurant',
       'AZN Sandwich Bar', 'Mr. Fuji Steakhouse and Sushi',
       "Mike & C's Family Sports Grill", 'Mellow Mushroom Peachtree City',
       'Crosstown Grille', 'The Curious Pig',
       'Smokey Bones Peachtree City', 'Basecamp at Kennesaw Mountain',
       'Padella Italian Atlanta', 'Checkers', 'Mi Rancho #2',
       'China Star', 'Marietta Crawfish', "Moe's Southwest Grill",
       'China Kitchen', 'Jerusalem Bakery & Grill', 'Night Life Pizza',
       "Church's Texas Chicken", 'El Velero Seafood & Mexican',
       'Haveli Indian Cuisine | Marietta', 'Imperial China Restaurant',
       'Cook Out', 'Philly & Wraps', 'El Pollo Dorado',
       'The Best Pizza Marietta', 'San Luis Restaurant',
       'PITA Mediterranean Street Food-Marietta Square',
       "Martin's Restaurant", 'CASITA MEXICAN KITCHEN & MARGARITA BAR',
       'MamiTaco', 'Los Bravos Mexican Restaurant', 'Forno Vero',
       'PONKO Chicken Marietta Square Market',
       "Lucky's Burger & Brew Marietta", 'Marietta Burger Bar',
       'Shai Karr Eatery', 'Red Elephant Thai Cuisine',
       'El Ranchero Mexican Restaurant', 'Viva Mexico Mexican Restaurant',
       "Don Pedro's Mexican Restaurant", 'Crooked Tree Cafe',
       'Blue Moon Pizza', '3 Amigos Mexican Bar & Grill',
       'Marietta Pizza Co', 'The Eating Spot',
       'WEI SICHUAN AUTHENTIC CHINESE CUISINE', 'Siete Tacos + Tequila',
       'Lemon Grass Thai Restaurant', "Mac's Chop House",
       'Pappadeaux Seafood Kitchen', 'The Red Eyed Mule', 'House of Lu',
       'Hoboken Cafe on Whitlock', 'Stockyard Burgers and Bones',
       'Spring Restaurant', 'Piastra Restaurant',
       'Madras Mantra Marietta', 'Pollo Campero Marietta',
       'Costa Mar Seafood & Grill', 'Ege Sushi & Japanese Cuisine',
       'Twisted Kitchen Marietta',
       'Monterrey Mexican Restaurant Marietta', 'WR Social House',
       'Mezza Luna Pasta & Seafood', 'L On North'], dtype=object)

In [ ]:
# TODO: Clustered Bar plot: reviews per restaurant (sorted descending — maybe top 20) (2 bars per restaurant -> total reviews (reviewsCount) + total reviews analysed (sum of reviews per restaurant)).

In [15]:
# TODO: Pie chart / countplot: proportion of restaurants with multiple categories.
dataset.groupby('title')['categoryName'].nunique().sort_values(ascending=False)

title
J. Christopher's                   2
3 Amigos Mexican Bar & Grill       1
No Mas! Cantina                    1
Olive Garden Italian Restaurant    1
Old Lady Gang Southern Cuisine     1
                                  ..
Goto                               1
Good ol' Days Bar and Grill        1
Georgia Shrimp Co                  1
Fridas Mexican Cuisine             1
il Giallo Osteria & Bar            1
Name: categoryName, Length: 295, dtype: int64

## 3. Cuisine Types (categoryName)

In [24]:
# TODO: How many unique categories?
dataset['categoryName'].nunique()

19

In [10]:
# TODO: Which categories do we have?
dataset['categoryName'].unique()

array(['Seafood restaurant', 'Italian restaurant', 'Mexican restaurant',
       'New American restaurant', 'Japanese restaurant',
       'Fast food restaurant', 'American restaurant',
       'Hamburger restaurant', 'Breakfast restaurant',
       'Indian restaurant', 'Mediterranean restaurant', 'Thai restaurant',
       'Steak house', 'Barbecue restaurant', 'Bar & grill',
       'Chinese restaurant', 'Pizza restaurant', 'Chicken restaurant',
       'Sandwich shop'], dtype=object)

In [ ]:
# TODO: How many restaurants per category?
restaurants_per_category = dataset['title'].groupby(dataset['categoryName']).nunique().reset_index()
restaurants_per_category.columns = ['Category', 'Number of Restaurants']
restaurants_per_category = restaurants_per_category.sort_values(by='Number of Restaurants', ascending=False)
restaurants_per_category

bar_chart(restaurants_per_category, 'Category', 'Number of Restaurants', 'Number of Restaurants per Category', labels={'Number of Restaurants': 'Number of Restaurants', 'Category': 'Category'})

In [ ]:
# TODO: See if there are meaningful patterns in website presence/absence across categories.

In [ ]:
# TODO: Clustered Bar plot: reviews per category (sorted descending — maybe top 20) (2 bars per category -> total reviews (reviewsCount) + total reviews analysed (sum of reviews per category)).

In [ ]:
# TODO: Which cuisines are most/least represented?

In [ ]:
# TODO: Bar chart (horizontal) of restaurant count per category (sorted).

In [ ]:
# TODO: Treemap or word cloud of cuisine frequency — more visual appeal.

In [ ]:
# TODO: Heatmap (if multi-category exists): co-occurrence matrix of cuisines per restaurant.

## 4. Ratings & Reviews

In [ ]:
# TODO: What’s the overall distribution of stars?

In [ ]:
# TODO: Are there categories that systematically get higher/lower ratings?

In [ ]:
# TODO: Is there a relationship between reviewsCount and stars?

In [ ]:
# TODO: Which restaurants have extreme ratings (5.0 or <3.0) and many reviews?

In [ ]:
# TODO: See if there are meaningful patterns in website presence/absence across star ratings.

In [ ]:
#TODO: Histogram / KDE of stars.

In [ ]:
#TODO: Boxplot or violin plot: stars by categoryName.

In [ ]:
#TODO: Scatter plot: reviewsCount vs stars (size = avg review length maybe).

In [ ]:
# TODO: rating per restaurant
dataset.groupby('title')['stars'].describe()

                           count      mean       std  min  25%  50%  75%  max
categoryName
American restaurant       5049.0  4.220440  1.308092  1.0  4.0  5.0  5.0  5.0
Bar & grill               1107.0  4.274616  1.226042  1.0  4.0  5.0  5.0  5.0
Barbecue restaurant       1139.0  4.266023  1.281337  1.0  4.0  5.0  5.0  5.0
Breakfast restaurant      2491.0  4.173826  1.344890  1.0  4.0  5.0  5.0  5.0
Chicken restaurant        1780.0  3.482022  1.700845  1.0  1.0  4.0  5.0  5.0
Chinese restaurant        2484.0  3.842593  1.554417  1.0  3.0  5.0  5.0  5.0
Fast food restaurant      5325.0  3.369014  1.696656  1.0  1.0  4.0  5.0  5.0
Hamburger restaurant      1979.0  4.156645  1.337686  1.0  4.0  5.0  5.0  5.0
Indian restaurant         1753.0  4.174558  1.376703  1.0  4.0  5.0  5.0  5.0
Italian restaurant        5108.0  4.322631  1.253802  1.0  4.0  5.0  5.0  5.0
Japanese restaurant       1533.0  4.117417  1.415797  1.0  4.0  5.0  5.0  5.0
Mediterranean restaurant  1450.0  4.315172  1.284017  1.0  4.0  5.0  5.0  5.0
Mexican restaurant        8959.0  4.061502  1.448957  1.0  3.0  5.0  5.0  5.0
New American restaurant   1903.0  4.291645  1.229487  1.0  4.0  5.0  5.0  5.0
Pizza restaurant          4560.0  4.105482  1.426127  1.0  4.0  5.0  5.0  5.0
Sandwich shop             1862.0  3.735231  1.618749  1.0  2.0  5.0  5.0  5.0
Seafood restaurant        2048.0  4.246582  1.277836  1.0  4.0  5.0  5.0  5.0
Steak house               1776.0  4.225788  1.328869  1.0  4.0  5.0  5.0  5.0
Thai restaurant           1260.0  4.257143  1.296628  1.0  4.0  5.0  5.0  5.0

In [ ]:
# TODO: rating per category
dataset.groupby('categoryName')['stars'].describe()

                           count      mean       std  min  25%  50%  75%  max
categoryName
American restaurant       5049.0  4.220440  1.308092  1.0  4.0  5.0  5.0  5.0
Bar & grill               1107.0  4.274616  1.226042  1.0  4.0  5.0  5.0  5.0
Barbecue restaurant       1139.0  4.266023  1.281337  1.0  4.0  5.0  5.0  5.0
Breakfast restaurant      2491.0  4.173826  1.344890  1.0  4.0  5.0  5.0  5.0
Chicken restaurant        1780.0  3.482022  1.700845  1.0  1.0  4.0  5.0  5.0
Chinese restaurant        2484.0  3.842593  1.554417  1.0  3.0  5.0  5.0  5.0
Fast food restaurant      5325.0  3.369014  1.696656  1.0  1.0  4.0  5.0  5.0
Hamburger restaurant      1979.0  4.156645  1.337686  1.0  4.0  5.0  5.0  5.0
Indian restaurant         1753.0  4.174558  1.376703  1.0  4.0  5.0  5.0  5.0
Italian restaurant        5108.0  4.322631  1.253802  1.0  4.0  5.0  5.0  5.0
Japanese restaurant       1533.0  4.117417  1.415797  1.0  4.0  5.0  5.0  5.0
Mediterranean restaurant  1450.0  4.315172  1.284017  1.0  4.0  5.0  5.0  5.0
Mexican restaurant        8959.0  4.061502  1.448957  1.0  3.0  5.0  5.0  5.0
New American restaurant   1903.0  4.291645  1.229487  1.0  4.0  5.0  5.0  5.0
Pizza restaurant          4560.0  4.105482  1.426127  1.0  4.0  5.0  5.0  5.0
Sandwich shop             1862.0  3.735231  1.618749  1.0  2.0  5.0  5.0  5.0
Seafood restaurant        2048.0  4.246582  1.277836  1.0  4.0  5.0  5.0  5.0
Steak house               1776.0  4.225788  1.328869  1.0  4.0  5.0  5.0  5.0
Thai restaurant           1260.0  4.257143  1.296628  1.0  4.0  5.0  5.0  5.0

## 5. Geographical Overview

In [ ]:
# TODO: Where are the restaurants located? (url field)

In [ ]:
# TODO: Do higher-rated categories cluster geographically?

In [ ]:
# TODO: Folium or Plotly map: restaurants colored by rating or category.

In [ ]:
# TODO: Density heatmap: concentration of restaurants across Atlanta.

## 6. Review Text Exploration

In [ ]:
# TODO: What’s the average review length?

In [ ]:
# TODO: Are there obvious language issues or emojis/symbols?

In [ ]:
# TODO: What are the most common words overall? By category?

In [ ]:
# TODO: Word cloud of most frequent words.

In [ ]:
# TODO: Bar plot of top 20 terms (using simple TF counts).

In [ ]:
# TODO: Maybe a simple sentiment distribution (TextBlob/VADER) for curiosity — though deeper sentiment analysis will come later.